import { useState, useRef, useEffect, useCallback } from 'react';
// @react-pdf/renderer — generates a real PDF blob for direct download
import { pdf } from '@react-pdf/renderer';
import { ResumeDocument } from './MyDocument';

// ─── Highlight JD keywords in text (returns JSX with <b> tags) ─────────────────
function highlightText(text, keywords) {
  if (!keywords?.length || !text) return text;

  const validKw = keywords.filter((k) => k && k.trim().length > 1);
  if (!validKw.length) return text;

  // Sort longest-first so "JavaScript" matches before "Java"
  const escaped = validKw
    .sort((a, b) => b.length - a.length)
    .map((k) => k.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));

  // Use word boundaries to avoid partial matches (e.g. "Java" inside "JavaScript")
  const regex = new RegExp(`\\b(${escaped.join('|')})\\b`, 'gi');
  const parts = text.split(regex);
  const kwLower = new Set(validKw.map((k) => k.toLowerCase()));

  return parts.map((part, i) =>
    kwLower.has(part.toLowerCase()) ? (
      <b key={i}>{part}</b>
    ) : (
      part
    )
  );
}

// ─── LaTeX special character escaping ──────────────────────────────────────────
function escapeLatex(str) {
  if (!str) return '';
  return str
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/&/g, '\\&')
    .replace(/%/g, '\\%')
    .replace(/\$/g, '\\$')
    .replace(/#/g, '\\#')
    .replace(/_/g, '\\_')
    .replace(/\{/g, '\\{')
    .replace(/\}/g, '\\}')
    .replace(/~/g, '\\textasciitilde{}')
    .replace(/\^/g, '\\textasciicircum{}');
}

// ─── Escape LaTeX AND bold JD keywords with \textbf ────────────────────────────
function texBoldKeywords(text, keywords) {
  if (!text) return '';
  if (!keywords?.length) return escapeLatex(text);

  const validKw = keywords.filter((k) => k && k.trim().length > 1);
  if (!validKw.length) return escapeLatex(text);

  const escaped = validKw
    .sort((a, b) => b.length - a.length)
    .map((k) => k.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));

  const regex = new RegExp(`\\b(${escaped.join('|')})\\b`, 'gi');
  const parts = text.split(regex);
  const kwLower = new Set(validKw.map((k) => k.toLowerCase()));

  return parts
    .map((part) =>
      kwLower.has(part.toLowerCase())
        ? `\\textbf{${escapeLatex(part)}}`
        : escapeLatex(part)
    )
    .join('');
}

// ─── Generate downloadable .tex source from resume JSON ────────────────────────
function generateLatexSource(data) {
  const e = escapeLatex;
  const kw = data.jd_keywords || [];
  const bk = (text) => texBoldKeywords(text, kw);

  let tex = `%-------------------------
% Resume generated by ResumeBuilder AI
% Based on Jake Gutierrez's LaTeX template
%-------------------------

\\documentclass[letterpaper,11pt]{article}

\\usepackage{latexsym}
\\usepackage[empty]{fullpage}
\\usepackage{titlesec}
\\usepackage{marvosym}
\\usepackage[usenames,dvipsnames]{color}
\\usepackage{verbatim}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage[english]{babel}
\\usepackage{tabularx}
\\usepackage{fontawesome5}
\\usepackage{multicol}
\\setlength{\\multicolsep}{-3.0pt}
\\setlength{\\columnsep}{-1pt}
\\input{glyphtounicode}

\\pagestyle{fancy}
\\fancyhf{}
\\fancyfoot{}
\\renewcommand{\\headrulewidth}{0pt}
\\renewcommand{\\footrulewidth}{0pt}

\\addtolength{\\oddsidemargin}{-0.6in}
\\addtolength{\\evensidemargin}{-0.5in}
\\addtolength{\\textwidth}{1.19in}
\\addtolength{\\topmargin}{-.7in}
\\addtolength{\\textheight}{1.4in}

\\urlstyle{same}
\\raggedbottom
\\raggedright
\\setlength{\\tabcolsep}{0in}

\\titleformat{\\section}{
  \\vspace{-4pt}\\scshape\\raggedright\\large\\bfseries
}{}{0em}{}[\\color{black}\\titlerule \\vspace{-5pt}]

\\pdfgentounicode=1

\\newcommand{\\resumeItem}[1]{\\item\\small{{#1 \\vspace{-2pt}}}}
\\newcommand{\\resumeSubheading}[4]{
  \\vspace{-2pt}\\item
    \\begin{tabular*}{1.0\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}
      \\textbf{#1} & \\textbf{\\small #2} \\\\
      \\textit{\\small#3} & \\textit{\\small #4} \\\\
    \\end{tabular*}\\vspace{-7pt}
}
\\newcommand{\\resumeProjectHeading}[2]{
    \\item
    \\begin{tabular*}{1.001\\textwidth}{l@{\\extracolsep{\\fill}}r}
      \\small#1 & \\textbf{\\small #2}\\\\
    \\end{tabular*}\\vspace{-7pt}
}
\\newcommand{\\resumeSubItem}[1]{\\resumeItem{#1}\\vspace{-4pt}}
\\renewcommand\\labelitemi{$\\vcenter{\\hbox{\\tiny$\\bullet$}}$}
\\renewcommand\\labelitemii{$\\vcenter{\\hbox{\\tiny$\\bullet$}}$}
\\newcommand{\\resumeSubHeadingListStart}{\\begin{itemize}[leftmargin=0.0in, label={}]}
\\newcommand{\\resumeSubHeadingListEnd}{\\end{itemize}}
\\newcommand{\\resumeItemListStart}{\\begin{itemize}}
\\newcommand{\\resumeItemListEnd}{\\end{itemize}\\vspace{-5pt}}

\\begin{document}

`;

  // ── Heading ──
  tex += `\\begin{center}\n    {\\Huge \\scshape ${e(data.name || '')}} \\\\ \\vspace{1pt}\n`;
  if (data.location) tex += `    ${e(data.location)} \\\\ \\vspace{1pt}\n`;
  tex += `    \\small`;
  if (data.phone) tex += ` \\raisebox{-0.1\\height}\\faPhone\\ ${e(data.phone)}`;
  if (data.email) tex += ` ~ \\href{mailto:${data.email}}{\\raisebox{-0.2\\height}\\faEnvelope\\  \\underline{${e(data.email)}}}`;
  if (data.linkedin) tex += ` ~ \\href{https://${data.linkedin.replace(/^https?:\/\//, '')}}{\\raisebox{-0.2\\height}\\faLinkedin\\ \\underline{${e(data.linkedin)}}}`;
  if (data.github) tex += ` ~ \\href{https://${data.github.replace(/^https?:\/\//, '')}}{\\raisebox{-0.2\\height}\\faGithub\\ \\underline{${e(data.github)}}}`;
  if (data.portfolio) tex += ` ~ \\href{https://${data.portfolio.replace(/^https?:\/\//, '')}}{\\raisebox{-0.2\\height}\\faGlobe\\ \\underline{${e(data.portfolio)}}}`;
  tex += `\n    \\vspace{-8pt}\n\\end{center}\n\n`;

  // ── Summary ──
  if (data.summary) {
    tex += `\\section{Summary}\n\\small{${bk(data.summary)}}\n\\vspace{-5pt}\n\n`;
  }

  // ── Education ──
  if (data.education?.length) {
    tex += `\\section{Education}\n  \\resumeSubHeadingListStart\n`;
    for (const edu of data.education) {
      tex += `    \\resumeSubheading\n      {${e(edu.school || edu.institution || '')}}{${e(edu.year || '')}}\n      {${e(edu.degree || '')}}{${e(edu.location || '')}${edu.gpa ? ' -- GPA: ' + e(edu.gpa) : ''}}\n`;
    }
    tex += `  \\resumeSubHeadingListEnd\n\n`;
    const cw = data.education[0]?.coursework;
    if (cw?.length) {
      tex += `\\section{Relevant Coursework}\n    \\begin{multicols}{4}\n        \\begin{itemize}[itemsep=-5pt, parsep=3pt]\n`;
      for (const c of cw) tex += `            \\item\\small ${e(c)}\n`;
      tex += `        \\end{itemize}\n    \\end{multicols}\n    \\vspace*{2.0\\multicolsep}\n\n`;
    }
  }

  // ── Experience ──
  if (data.experience?.length) {
    tex += `\\section{Experience}\n  \\resumeSubHeadingListStart\n\n`;
    for (const exp of data.experience) {
      tex += `    \\resumeSubheading\n      {${e(exp.company || '')}}{${e(exp.duration || '')}}\n      {${e(exp.title || exp.role || '')}}{${e(exp.location || '')}}\n`;
      if (exp.bullets?.length) {
        tex += `      \\resumeItemListStart\n`;
        for (const b of exp.bullets) tex += `        \\resumeItem{${bk(b)}}\n`;
        tex += `      \\resumeItemListEnd\n\n`;
      }
    }
    tex += `  \\resumeSubHeadingListEnd\n\\vspace{-16pt}\n\n`;
  }

  // ── Projects ──
  if (data.projects?.length) {
    tex += `\\section{Projects}\n    \\vspace{-5pt}\n    \\resumeSubHeadingListStart\n`;
    for (const proj of data.projects) {
      const tech = Array.isArray(proj.techStack) ? proj.techStack.join(', ') : proj.tech || '';
      tex += `      \\resumeProjectHeading\n          {\\textbf{${e(proj.name)}} $|$ \\emph{${e(tech)}}}{${e(proj.date || '')}}\n`;
      tex += `          \\resumeItemListStart\n`;
      const bullets = proj.bullets?.length ? proj.bullets : proj.description ? [proj.description] : [];
      for (const b of bullets) tex += `            \\resumeItem{${bk(b)}}\n`;
      tex += `          \\resumeItemListEnd\n          \\vspace{-13pt}\n`;
    }
    tex += `    \\resumeSubHeadingListEnd\n\\vspace{-15pt}\n\n`;
  }

  // ── Technical Skills (categorized) ──
  if (data.skill_categories && Object.keys(data.skill_categories).length) {
    tex += `\\section{Technical Skills}\n \\begin{itemize}[leftmargin=0.15in, label={}]\n    \\small{\\item{\n`;
    for (const [cat, arr] of Object.entries(data.skill_categories)) {
      if (arr?.length) tex += `     \\textbf{${e(cat)}}{: ${arr.map(e).join(', ')}} \\\\\n`;
    }
    tex += `    }}\n \\end{itemize}\n \\vspace{-16pt}\n\n`;
  } else if (data.skills?.length) {
    tex += `\\section{Technical Skills}\n \\begin{itemize}[leftmargin=0.15in, label={}]\n    \\small{\\item{\n     \\textbf{Skills}{: ${data.skills.map(e).join(', ')}} \\\\\n    }}\n \\end{itemize}\n \\vspace{-16pt}\n\n`;
  }

  // ── Certifications ──
  if (data.certifications?.length) {
    tex += `\\section{Certifications}\n  \\resumeSubHeadingListStart\n`;
    for (const cert of data.certifications) {
      if (typeof cert === 'string') tex += `    \\resumeSubItem{${e(cert)}}\n`;
      else tex += `    \\resumeSubheading{${e(cert.name || '')}}{${e(cert.year || '')}}{${e(cert.issuer || '')}}{}\n`;
    }
    tex += `  \\resumeSubHeadingListEnd\n\n`;
  }

  // ── Languages ──
  if (data.languages?.length) {
    tex += `\\section{Languages}\n \\begin{itemize}[leftmargin=0.15in, label={}]\n    \\small{\\item{${data.languages.map(e).join(', ')}}}\n \\end{itemize}\n\\vspace{-16pt}\n\n`;
  }

  // ── Awards ──
  if (data.awards?.length) {
    tex += `\\section{Awards}\n  \\resumeItemListStart\n`;
    for (const a of data.awards) tex += `    \\resumeItem{${e(typeof a === 'string' ? a : a.name || JSON.stringify(a))}}\n`;
    tex += `  \\resumeItemListEnd\n\n`;
  }

  // ── Volunteer / Leadership ──
  if (data.volunteer?.length) {
    tex += `\\section{Leadership / Extracurricular}\n  \\resumeSubHeadingListStart\n`;
    for (const vol of data.volunteer) {
      if (typeof vol === 'string') tex += `    \\resumeSubItem{${e(vol)}}\n`;
      else {
        tex += `    \\resumeSubheading{${e(vol.organization || vol.name || '')}}{${e(vol.duration || '')}}{${e(vol.role || vol.title || '')}}{${e(vol.location || '')}}\n`;
        if (vol.bullets?.length) {
          tex += `      \\resumeItemListStart\n`;
          for (const b of vol.bullets) tex += `        \\resumeItem{${e(b)}}\n`;
          tex += `      \\resumeItemListEnd\n`;
        }
      }
    }
    tex += `  \\resumeSubHeadingListEnd\n\n`;
  }

  tex += `\\end{document}\n`;
  return tex;
}

// ─── App Component ─────────────────────────────────────────────────────────────
function App() {
  const [leftWidth, setLeftWidth] = useState(42);
  const [isDragging, setIsDragging] = useState(false);
  const [jobDescription, setJobDescription] = useState('');
  const [uploadedFile, setUploadedFile] = useState(null);
  const [isDragOver, setIsDragOver] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [resumeData, setResumeData] = useState(null);
  const [error, setError] = useState(null);
  // Tracks PDF generation state for the download button
  const [isPdfGenerating, setIsPdfGenerating] = useState(false);

  const containerRef = useRef(null);
  const fileInputRef = useRef(null);

  // ── Drag Logic ─────────────────────────────────────────────────────────────
  const handleMouseDown = useCallback((e) => {
    e.preventDefault();
    setIsDragging(true);
  }, []);

  useEffect(() => {
    const handleMouseMove = (e) => {
      if (!isDragging || !containerRef.current) return;
      const rect = containerRef.current.getBoundingClientRect();
      const pct = ((e.clientX - rect.left) / rect.width) * 100;
      setLeftWidth(Math.min(75, Math.max(25, pct)));
    };
    const handleMouseUp = () => setIsDragging(false);
    if (isDragging) {
      window.addEventListener('mousemove', handleMouseMove);
      window.addEventListener('mouseup', handleMouseUp);
    }
    return () => {
      window.removeEventListener('mousemove', handleMouseMove);
      window.removeEventListener('mouseup', handleMouseUp);
    };
  }, [isDragging]);

  // ── File Handlers ──────────────────────────────────────────────────────────
  const handleFileSelect = (e) => {
    const file = e.target.files?.[0];
    if (file) { setUploadedFile(file); setError(null); }
  };
  const handleDrop = (e) => {
    e.preventDefault(); setIsDragOver(false);
    const file = e.dataTransfer.files?.[0];
    if (file) { setUploadedFile(file); setError(null); }
  };
  const handleDragOver = (e) => { e.preventDefault(); setIsDragOver(true); };
  const handleDragLeave = () => setIsDragOver(false);
  const removeFile = () => {
    setUploadedFile(null);
    if (fileInputRef.current) fileInputRef.current.value = '';
  };

  // ── Generate Resume — backend call ─────────────────────────────────────────
  const handleGenerate = async () => {
    if (!uploadedFile) { setError('Please upload a resume file first.'); return; }
    setIsLoading(true);
    setError(null);
    try {
      const formData = new FormData();
      formData.append('uploaded_file', uploadedFile);
      formData.append('jobDescription', jobDescription);
      const response = await fetch('/api/upload', { method: 'POST', body: formData });
      if (!response.ok) throw new Error(`Server error: ${response.status} ${response.statusText}`);
      const data = await response.json();
      if (data.raw) {
        try { setResumeData(JSON.parse(data.raw)); }
        catch { throw new Error('The AI response could not be parsed. Please try again.'); }
      } else {
        setResumeData(data);
      }
    } catch (err) {
      console.error('Generate failed:', err);
      setError(err.message || 'Something went wrong. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  // ── Update a field in resumeData by path (e.g. ['experience', 0, 'company']) ─
  const handleFieldUpdate = useCallback((path, newValue) => {
    setResumeData((prev) => {
      const copy = JSON.parse(JSON.stringify(prev));
      let obj = copy;
      for (let i = 0; i < path.length - 1; i++) obj = obj[path[i]];
      obj[path[path.length - 1]] = newValue;
      return copy;
    });
  }, []);

  // ── Delete an entire section or an item from an array ─────────────────────
  const handleDeleteSection = useCallback((key) => {
    setResumeData((prev) => {
      const copy = { ...prev };
      delete copy[key];
      return copy;
    });
  }, []);

  const handleDeleteItem = useCallback((arrayKey, index, nestedPath) => {
    setResumeData((prev) => {
      const copy = JSON.parse(JSON.stringify(prev));
      let arr = copy;
      if (nestedPath) {
        for (const k of nestedPath) arr = arr[k];
      } else {
        arr = copy[arrayKey];
      }
      if (Array.isArray(arr)) arr.splice(index, 1);
      return copy;
    });
  }, []);

  // ── Download PDF (direct download via @react-pdf/renderer — no print dialog)
  const handleDownloadPDF = async () => {
    if (!resumeData || isPdfGenerating) return;
    setIsPdfGenerating(true);
    try {
      // Generate a PDF blob from our ResumeDocument component
      const blob = await pdf(<ResumeDocument data={resumeData} />).toBlob();
      // Create a temporary download link and trigger the download
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${(resumeData.name || 'resume').replace(/\s+/g, '_')}_Resume.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('PDF generation failed:', err);
      setError('Failed to generate PDF. Please try again.');
    } finally {
      setIsPdfGenerating(false);
    }
  };

  // ── Download .tex ──────────────────────────────────────────────────────────
  const handleDownloadTex = () => {
    if (!resumeData) return;
    const tex = generateLatexSource(resumeData);
    const blob = new Blob([tex], { type: 'application/x-tex' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${(resumeData.name || 'resume').replace(/\s+/g, '_')}_Resume.tex`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // ── Render ─────────────────────────────────────────────────────────────────
  return (
    <div
      ref={containerRef}
      className={`app-container flex h-screen w-screen bg-gray-50 overflow-hidden font-['Inter',sans-serif] ${
        isDragging ? 'cursor-col-resize select-none' : ''
      }`}
    >
      {/* ═══════════════════ LEFT PANEL ═══════════════════════════════════ */}
      <div
        id="left-panel"
        style={{ width: `${leftWidth}%` }}
        className="h-full flex flex-col bg-white border-r border-gray-100"
      >
        <div className="px-8 pt-8 pb-4">
          <div className="flex items-center gap-3 mb-1">
            <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-blue-500 to-indigo-600 flex items-center justify-center shadow-lg shadow-blue-500/25">
              <svg className="w-5 h-5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
            </div>
            <div>
              <h1 className="text-xl font-bold text-gray-900 tracking-tight">Resume Builder</h1>
              <p className="text-xs text-gray-400 font-medium">AI-powered • Tailored to the job</p>
            </div>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto px-8 pb-8 space-y-6">
          {/* File Upload */}
          <div>
            <label className="block text-sm font-semibold text-gray-700 mb-2">Upload Resume</label>
            <div
              onDrop={handleDrop} onDragOver={handleDragOver} onDragLeave={handleDragLeave}
              onClick={() => fileInputRef.current?.click()}
              className={`relative border-2 border-dashed rounded-2xl p-8 text-center cursor-pointer transition-all duration-200 ${
                isDragOver ? 'border-blue-400 bg-blue-50/80 scale-[1.01]'
                : uploadedFile ? 'border-emerald-300 bg-emerald-50/50'
                : 'border-gray-200 bg-gray-50/50 hover:border-blue-300 hover:bg-blue-50/40'
              }`}
            >
              <input ref={fileInputRef} type="file" accept=".pdf,.doc,.docx,.txt" onChange={handleFileSelect} className="hidden" />
              {uploadedFile ? (
                <div className="flex flex-col items-center gap-2">
                  <div className="w-12 h-12 rounded-full bg-emerald-100 flex items-center justify-center">
                    <svg className="w-6 h-6 text-emerald-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                    </svg>
                  </div>
                  <p className="text-sm font-medium text-gray-800 truncate max-w-[250px]">{uploadedFile.name}</p>
                  <p className="text-xs text-gray-400">{(uploadedFile.size / 1024).toFixed(1)} KB</p>
                  <button onClick={(e) => { e.stopPropagation(); removeFile(); }} className="text-xs text-red-500 hover:text-red-700 font-medium mt-1 transition-colors">Remove file</button>
                </div>
              ) : (
                <div className="flex flex-col items-center gap-3">
                  <div className="w-12 h-12 rounded-full bg-blue-100/80 flex items-center justify-center">
                    <svg className="w-6 h-6 text-blue-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5m-13.5-9L12 3m0 0l4.5 4.5M12 3v13.5" />
                    </svg>
                  </div>
                  <div>
                    <p className="text-sm font-medium text-gray-600">Drag & drop your resume here</p>
                    <p className="text-xs text-gray-400 mt-1">PDF, DOC, DOCX, or TXT • Max 10MB</p>
                  </div>
                  <span className="inline-block mt-1 text-xs font-semibold text-blue-600 bg-blue-50 px-4 py-1.5 rounded-full">Browse Files</span>
                </div>
              )}
            </div>
          </div>

          {/* Job Description */}
          <div>
            <label className="block text-sm font-semibold text-gray-700 mb-2">Job Description</label>
            <textarea
              value={jobDescription} onChange={(e) => setJobDescription(e.target.value)}
              placeholder="Paste or write job description here..."
              rows={10}
              className="w-full rounded-2xl border border-gray-200 bg-gray-50/50 px-5 py-4 text-sm text-gray-700 placeholder-gray-400 resize-none focus:outline-none focus:ring-2 focus:ring-blue-500/30 focus:border-blue-400 transition-all duration-200"
            />
            <p className="text-xs text-gray-400 mt-1.5 text-right">{jobDescription.length} characters</p>
          </div>

          {/* Error */}
          {error && (
            <div className="flex items-start gap-2 p-3 rounded-xl bg-red-50 border border-red-100">
              <svg className="w-5 h-5 text-red-500 flex-shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z" />
              </svg>
              <p className="text-sm text-red-600">{error}</p>
            </div>
          )}

          {/* Generate Button */}
          <button
            onClick={handleGenerate} disabled={isLoading}
            className="w-full py-3.5 rounded-2xl text-white font-semibold text-sm bg-gradient-to-r from-blue-500 to-indigo-600 hover:from-blue-600 hover:to-indigo-700 active:scale-[0.98] disabled:opacity-70 disabled:cursor-not-allowed shadow-lg shadow-blue-500/25 hover:shadow-blue-500/40 transition-all duration-200 flex items-center justify-center gap-2"
          >
            {isLoading ? (
              <>
                <svg className="animate-spin h-5 w-5 text-white" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                </svg>
                Generating…
              </>
            ) : (
              <>
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M13 10V3L4 14h7v7l9-11h-7z" />
                </svg>
                Generate Resume
              </>
            )}
          </button>
        </div>
      </div>

      {/* ═══════════════════ DIVIDER ══════════════════════════════════════ */}
      <div
        id="panel-divider"
        onMouseDown={handleMouseDown}
        className={`w-1.5 flex-shrink-0 cursor-col-resize relative group transition-colors duration-150 ${
          isDragging ? 'bg-blue-400' : 'bg-gray-200 hover:bg-blue-300'
        }`}
      >
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 flex flex-col gap-1">
          {[0, 1, 2].map((i) => (
            <span key={i} className={`block w-1 h-1 rounded-full transition-colors ${isDragging ? 'bg-white' : 'bg-gray-400 group-hover:bg-blue-500'}`} />
          ))}
        </div>
      </div>

      {/* ═══════════════════ RIGHT PANEL ══════════════════════════════════ */}
      <div
        id="right-panel"
        style={{ width: `${100 - leftWidth}%` }}
        className="h-full flex flex-col bg-gray-100"
      >
        {/* Panel Header (hidden during print) */}
        <div className="panel-header px-8 pt-6 pb-3 flex items-center justify-between bg-gray-100">
          <div>
            <h2 className="text-lg font-bold text-gray-900 tracking-tight">Preview</h2>
            <p className="text-xs text-gray-400 font-medium">
              {resumeData ? 'ATS-optimized resume with bolded keywords' : 'Your generated resume will appear here'}
            </p>
          </div>
          {resumeData && (
            <div className="flex items-center gap-2">
              {/* Primary: Download PDF (direct download, no print dialog) */}
              <button
                onClick={handleDownloadPDF}
                disabled={isPdfGenerating}
                title="Download resume as PDF"
                className={`inline-flex items-center gap-2 text-sm font-semibold text-white bg-gradient-to-r from-emerald-500 to-teal-600 hover:from-emerald-600 hover:to-teal-700 px-5 py-2.5 rounded-xl shadow-lg shadow-emerald-500/25 hover:shadow-emerald-500/40 active:scale-[0.97] transition-all duration-200 ${isPdfGenerating ? 'opacity-70 cursor-not-allowed' : ''}`}
              >
                {isPdfGenerating ? (
                  <svg className="animate-spin w-4 h-4 text-white" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                  </svg>
                ) : (
                  <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
                  </svg>
                )}
                {isPdfGenerating ? 'Generating PDF…' : 'Download PDF'}
              </button>
              {/* Secondary: Download .tex */}
              <button
                onClick={handleDownloadTex}
                className="inline-flex items-center gap-1.5 text-xs font-semibold text-gray-600 bg-white border border-gray-200 hover:bg-gray-50 hover:border-gray-300 px-3.5 py-2.5 rounded-xl transition-all duration-200"
              >
                <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m.75 12l3 3m0 0l3-3m-3 3v-6m-1.5-9H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
                </svg>
                .tex
              </button>
            </div>
          )}
        </div>

        {/* Resume Content (scrollable, multi-page when printed) */}
        <div className="flex-1 overflow-y-auto px-6 pb-8 resume-scroll">
          {!resumeData ? (
            <div className="h-full flex flex-col items-center justify-center text-center">
              <div className="w-20 h-20 rounded-3xl bg-gray-200 flex items-center justify-center mb-5">
                <svg className="w-10 h-10 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
                </svg>
              </div>
              <h3 className="text-base font-semibold text-gray-500 mb-2">No resume generated yet</h3>
              <p className="text-sm text-gray-400 max-w-xs leading-relaxed">
                Upload your resume and paste a job description, then click
                <span className="font-semibold text-blue-500"> Generate Resume </span>
                to see the magic.
              </p>
            </div>
          ) : (
            <LatexResumePreview
              data={resumeData}
              onUpdate={handleFieldUpdate}
              onDeleteSection={handleDeleteSection}
              onDeleteItem={handleDeleteItem}
            />
          )}
        </div>
      </div>
    </div>
  );
}

// ─── Editable text helper ──────────────────────────────────────────────────────
function Editable({ value, onSave, className, tag: Tag = 'span', children }) {
  const handleBlur = (e) => {
    const newText = e.target.innerText.trim();
    if (newText !== value && onSave) onSave(newText);
  };
  return (
    <Tag
      contentEditable
      suppressContentEditableWarning
      onBlur={handleBlur}
      className={`editable-field ${className || ''}`}
    >
      {children || value}
    </Tag>
  );
}

// ─── Section delete button ────────────────────────────────────────────────────
function DeleteSectionBtn({ onClick, title }) {
  return (
    <button
      onClick={onClick}
      className="section-delete-btn"
      title={title || 'Delete section'}
    >
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
        <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
      </svg>
    </button>
  );
}

// ─── Item delete button (for individual entries/bullets) ──────────────────────
function DeleteItemBtn({ onClick, title }) {
  return (
    <button
      onClick={(e) => { e.stopPropagation(); onClick(); }}
      className="item-delete-btn"
      title={title || 'Delete item'}
    >
      <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
        <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
      </svg>
    </button>
  );
}

// ─── Section header with title + delete button ────────────────────────────────
function SectionHeader({ title, onDelete }) {
  return (
    <div className="section-header-wrapper">
      <LatexSectionTitle>{title}</LatexSectionTitle>
      {onDelete && <DeleteSectionBtn onClick={onDelete} title={`Delete ${title}`} />}
    </div>
  );
}

// ─── LaTeX-Styled Resume Preview ───────────────────────────────────────────────
function LatexResumePreview({ data, onUpdate, onDeleteSection, onDeleteItem }) {
  // Merge jd_keywords + skills for highlighting
  const keywords = [...new Set([
    ...(data.jd_keywords || []),
    ...(data.skills || []),
    ...(data.skill_categories ? Object.values(data.skill_categories).flat() : []),
  ])];
  const hl = (text) => highlightText(text, keywords);

  // Helper: save a field at a given path
  const save = (...path) => (newVal) => onUpdate(path, newVal);

  // Collect known keys to find any extra sections
  // Profile link keys are treated as contact-row items, not standalone sections
  const profileLinkKeys = [
    'leetcode', 'codechef', 'codeforces', 'hackerrank',
    'hackerearth', 'kaggle', 'medium', 'twitter', 'dribbble',
    'behance', 'stackoverflow', 'website',
  ];
  const knownKeys = new Set([
    'name','email','phone','location','linkedin','github','portfolio','title',
    'summary','skills','skill_categories','experience','education',
    'projects','certifications','languages','awards','volunteer',
    'jd_keywords','raw', ...profileLinkKeys,
  ]);
  const extraSections = Object.keys(data).filter((k) => !knownKeys.has(k) && data[k]);

  return (
    <div
      id="resume-preview"
      className="latex-resume bg-white shadow-xl border border-gray-200 mx-auto mt-2 mb-6"
      style={{ maxWidth: '816px', padding: '48px 56px' }}
    >
      {/* ── HEADING ────────────────────────────────────────────────────── */}
      <div className="text-center mb-1">
        <h1 className="latex-name">
          <Editable value={data.name} onSave={save('name')}>{data.name}</Editable>
        </h1>
        {data.location && (
          <p className="text-[0.85em] mt-0.5">
            <Editable value={data.location} onSave={save('location')}>{data.location}</Editable>
          </p>
        )}
        <div className="latex-contact-row mt-1.5">
          {data.phone && <Editable tag="span" value={data.phone} onSave={save('phone')} className="flex items-center gap-1"><PhoneIcon />{data.phone}</Editable>}
          {data.email && <Editable tag="span" value={data.email} onSave={save('email')} className="flex items-center gap-1"><EnvelopeIcon />{data.email}</Editable>}
          {data.linkedin && <Editable tag="span" value={data.linkedin} onSave={save('linkedin')} className="flex items-center gap-1"><LinkedInIcon />{data.linkedin}</Editable>}
          {data.github && <Editable tag="span" value={data.github} onSave={save('github')} className="flex items-center gap-1"><GitHubIcon />{data.github}</Editable>}
          {data.portfolio && <Editable tag="span" value={data.portfolio} onSave={save('portfolio')} className="flex items-center gap-1"><GlobeIcon />{data.portfolio}</Editable>}
          {/* Extra profile links (LeetCode, CodeChef, etc.) */}
          {profileLinkKeys.map((key) =>
            data[key] ? (
              <Editable key={key} tag="span" value={data[key]} onSave={save(key)} className="flex items-center gap-1">
                <GlobeIcon />{data[key]}
              </Editable>
            ) : null
          )}
        </div>
      </div>

      {/* ── SUMMARY ────────────────────────────────────────────────────── */}
      {data.summary && (
        <div className="entry-avoid-break">
          <SectionHeader title="Summary" onDelete={() => onDeleteSection('summary')} />
          <Editable tag="p" value={data.summary} onSave={save('summary')} className="text-[0.92em] leading-relaxed">{hl(data.summary)}</Editable>
        </div>
      )}

      {/* ── EDUCATION ──────────────────────────────────────────────────── */}
      {data.education?.length > 0 && (
        <>
          <SectionHeader title="Education" onDelete={() => onDeleteSection('education')} />
          {data.education.map((edu, i) => (
            <div key={i} className="mb-1 entry-avoid-break item-wrapper">
              <DeleteItemBtn onClick={() => onDeleteItem('education', i)} title="Delete this education" />
              <div className="latex-subheading-row">
                <Editable className="font-bold text-[0.95em]" value={edu.school || edu.institution || ''} onSave={save('education', i, 'school')}>{edu.school || edu.institution}</Editable>
                <Editable className="font-bold text-[0.85em]" value={edu.year || ''} onSave={save('education', i, 'year')}>{edu.year}</Editable>
              </div>
              <div className="latex-subheading-row">
                <Editable className="italic text-[0.85em]" value={edu.degree || ''} onSave={save('education', i, 'degree')}>{edu.degree}</Editable>
                <Editable className="italic text-[0.85em]" value={`${edu.location || ''}${edu.gpa ? ` — GPA: ${edu.gpa}` : ''}`} onSave={(v) => onUpdate(['education', i, 'location'], v)}>{edu.location}{edu.gpa && ` — GPA: ${edu.gpa}`}</Editable>
              </div>
            </div>
          ))}
          {data.education[0]?.coursework?.length > 0 && (
            <div className="entry-avoid-break">
              <SectionHeader title="Relevant Coursework" onDelete={() => {
                onUpdate(['education', 0, 'coursework'], []);
              }} />
              <ul className="latex-coursework-grid">
                {data.education[0].coursework.map((c, i) => (
                  <li key={i} className="item-wrapper">
                    <Editable value={c} onSave={save('education', 0, 'coursework', i)}>{c}</Editable>
                    <DeleteItemBtn onClick={() => onDeleteItem(null, i, ['education', 0, 'coursework'])} title="Remove course" />
                  </li>
                ))}
              </ul>
            </div>
          )}
        </>
      )}

      {/* ── EXPERIENCE ─────────────────────────────────────────────────── */}
      {data.experience?.length > 0 && (
        <>
          <SectionHeader title="Experience" onDelete={() => onDeleteSection('experience')} />
          {data.experience.map((exp, i) => (
            <div key={i} className="mb-2 entry-avoid-break item-wrapper">
              <DeleteItemBtn onClick={() => onDeleteItem('experience', i)} title="Delete this experience" />
              <div className="latex-subheading-row">
                <Editable className="font-bold text-[0.95em]" value={exp.company || ''} onSave={save('experience', i, 'company')}>{exp.company}</Editable>
                <Editable className="font-bold text-[0.85em]" value={exp.duration || ''} onSave={save('experience', i, 'duration')}>{exp.duration}</Editable>
              </div>
              <div className="latex-subheading-row">
                <Editable className="italic text-[0.85em]" value={exp.title || exp.role || ''} onSave={save('experience', i, 'title')}>{exp.title || exp.role}</Editable>
                <Editable className="italic text-[0.85em]" value={exp.location || ''} onSave={save('experience', i, 'location')}>{exp.location}</Editable>
              </div>
              {exp.bullets?.length > 0 && (
                <ul className="latex-bullets">
                  {exp.bullets.map((b, j) => (
                    <li key={j} className="bullet-wrapper">
                      <Editable tag="span" value={b} onSave={save('experience', i, 'bullets', j)}>{hl(b)}</Editable>
                      <DeleteItemBtn onClick={() => onDeleteItem(null, j, ['experience', i, 'bullets'])} title="Delete bullet" />
                    </li>
                  ))}
                </ul>
              )}
            </div>
          ))}
        </>
      )}

      {/* ── PROJECTS ───────────────────────────────────────────────────── */}
      {data.projects?.length > 0 && (
        <>
          <SectionHeader title="Projects" onDelete={() => onDeleteSection('projects')} />
          {data.projects.map((proj, i) => {
            const tech = Array.isArray(proj.techStack) ? proj.techStack.join(', ') : proj.tech || '';
            const bullets = proj.bullets?.length ? proj.bullets : proj.description ? [proj.description] : [];
            return (
              <div key={i} className="mb-2 entry-avoid-break item-wrapper">
                <DeleteItemBtn onClick={() => onDeleteItem('projects', i)} title="Delete this project" />
                <div className="latex-subheading-row">
                  <span className="text-[0.92em]">
                    <Editable className="font-bold" value={proj.name || ''} onSave={save('projects', i, 'name')}>{proj.name}</Editable>
                    {tech && <>{' | '}<Editable className="italic" value={tech} onSave={(v) => onUpdate(['projects', i, 'techStack'], v.split(',').map(s => s.trim()))}>{tech}</Editable></>}
                  </span>
                  {(proj.date || proj.year) && <Editable className="font-bold text-[0.85em]" value={proj.date || proj.year || ''} onSave={save('projects', i, 'date')}>{proj.date || proj.year}</Editable>}
                </div>
                {bullets.length > 0 && (
                  <ul className="latex-bullets">
                    {bullets.map((b, j) => (
                      <li key={j} className="bullet-wrapper">
                        <Editable tag="span" value={b} onSave={save('projects', i, 'bullets', j)}>{hl(b)}</Editable>
                        <DeleteItemBtn onClick={() => onDeleteItem(null, j, ['projects', i, 'bullets'])} title="Delete bullet" />
                      </li>
                    ))}
                  </ul>
                )}
                {proj.link && (proj.link.includes('.') || proj.link.startsWith('http')) && (
                  <p className="text-[0.85em] mt-0.5">
                    <a href={proj.link.startsWith('http') ? proj.link : `https://${proj.link}`} target="_blank" rel="noopener noreferrer" className="underline">{proj.link}</a>
                  </p>
                )}
              </div>
            );
          })}
        </>
      )}

      {/* ── TECHNICAL SKILLS (categorized or flat) ─────────────────────── */}
      {(data.skill_categories && Object.keys(data.skill_categories).length > 0) ? (
        <div className="entry-avoid-break">
          <SectionHeader title="Technical Skills" onDelete={() => { onDeleteSection('skill_categories'); onDeleteSection('skills'); }} />
          <ul className="latex-skills-list">
            {Object.entries(data.skill_categories).map(([cat, arr]) =>
              arr?.length > 0 && (
                <li key={cat} className="item-wrapper">
                  <DeleteItemBtn onClick={() => {
                    onUpdate(['skill_categories'], Object.fromEntries(
                      Object.entries(data.skill_categories).filter(([k]) => k !== cat)
                    ));
                  }} title={`Delete ${cat}`} />
                  <Editable
                    className="font-bold"
                    value={cat}
                    onSave={(newCat) => {
                      // Rename the category key
                      const updated = {};
                      for (const [k, v] of Object.entries(data.skill_categories)) {
                        updated[k === cat ? newCat : k] = v;
                      }
                      onUpdate(['skill_categories'], updated);
                    }}
                  >{cat}</Editable>:{' '}
                  <Editable
                    value={arr.join(', ')}
                    onSave={(v) => onUpdate(['skill_categories', cat], v.split(',').map(s => s.trim()).filter(Boolean))}
                  >
                    {arr.map((skill, i) => (
                      <span key={i}>
                        {i > 0 && ', '}
                        {data.jd_keywords?.some((k) => k.toLowerCase() === skill.toLowerCase())
                          ? <b>{skill}</b>
                          : skill
                        }
                      </span>
                    ))}
                  </Editable>
                </li>
              )
            )}
          </ul>
        </div>
      ) : data.skills?.length > 0 && (
        <div className="entry-avoid-break">
          <SectionHeader title="Technical Skills" onDelete={() => onDeleteSection('skills')} />
          <ul className="latex-skills-list">
            <li>
              <span className="font-bold">Skills</span>:{' '}
              <Editable
                value={data.skills.join(', ')}
                onSave={(v) => onUpdate(['skills'], v.split(',').map(s => s.trim()).filter(Boolean))}
              >
                {data.skills.map((skill, i) => (
                  <span key={i}>
                    {i > 0 && ', '}
                    {data.jd_keywords?.some((k) => k.toLowerCase() === skill.toLowerCase())
                      ? <b>{skill}</b>
                      : skill
                    }
                  </span>
                ))}
              </Editable>
            </li>
          </ul>
        </div>
      )}

      {/* ── CERTIFICATIONS ─────────────────────────────────────────────── */}
      {data.certifications?.length > 0 && (
        <div className="entry-avoid-break">
          <SectionHeader title="Certifications" onDelete={() => onDeleteSection('certifications')} />
          {data.certifications.map((cert, i) => (
            <div key={i} className="mb-1 item-wrapper">
              <DeleteItemBtn onClick={() => onDeleteItem('certifications', i)} title="Delete certification" />
              {typeof cert === 'string' ? (
                <Editable tag="p" className="text-[0.92em]" value={cert} onSave={(v) => {
                  onUpdate(['certifications', i], v);
                }}>{cert}</Editable>
              ) : (
                <>
                  <div className="latex-subheading-row">
                    <Editable className="font-bold text-[0.95em]" value={cert.name || ''} onSave={save('certifications', i, 'name')}>{cert.name}</Editable>
                    <Editable className="font-bold text-[0.85em]" value={cert.year || ''} onSave={save('certifications', i, 'year')}>{cert.year}</Editable>
                  </div>
                  {cert.issuer && <Editable tag="p" className="italic text-[0.85em]" value={cert.issuer} onSave={save('certifications', i, 'issuer')}>{cert.issuer}</Editable>}
                </>
              )}
            </div>
          ))}
        </div>
      )}

      {/* ── LANGUAGES ──────────────────────────────────────────────────── */}
      {data.languages?.length > 0 && (
        <div className="entry-avoid-break">
          <SectionHeader title="Languages" onDelete={() => onDeleteSection('languages')} />
          <ul className="latex-skills-list">
            <li>
              <Editable value={data.languages.join(', ')} onSave={(v) => onUpdate(['languages'], v.split(',').map(s => s.trim()))}>
                {data.languages.join(', ')}
              </Editable>
            </li>
          </ul>
        </div>
      )}

      {/* ── AWARDS ─────────────────────────────────────────────────────── */}
      {data.awards?.length > 0 && (
        <div className="entry-avoid-break">
          <SectionHeader title="Awards" onDelete={() => onDeleteSection('awards')} />
          <ul className="latex-bullets">
            {data.awards.map((a, i) => {
              const text = typeof a === 'string' ? a : a.name || JSON.stringify(a);
              return (
                <li key={i} className="bullet-wrapper">
                  <Editable tag="span" value={text} onSave={(v) => onUpdate(['awards', i], v)}>{text}</Editable>
                  <DeleteItemBtn onClick={() => onDeleteItem('awards', i)} title="Delete award" />
                </li>
              );
            })}
          </ul>
        </div>
      )}

      {/* ── VOLUNTEER / LEADERSHIP ─────────────────────────────────────── */}
      {data.volunteer?.length > 0 && (
        <>
          <SectionHeader title="Leadership / Extracurricular" onDelete={() => onDeleteSection('volunteer')} />
          {data.volunteer.map((vol, i) => (
            <div key={i} className="mb-2 entry-avoid-break item-wrapper">
              <DeleteItemBtn onClick={() => onDeleteItem('volunteer', i)} title="Delete this entry" />
              {typeof vol === 'string' ? (
                <Editable tag="p" className="text-[0.92em]" value={vol} onSave={save('volunteer', i)}>{vol}</Editable>
              ) : (
                <>
                  <div className="latex-subheading-row">
                    <Editable className="font-bold text-[0.95em]" value={vol.organization || vol.name || ''} onSave={save('volunteer', i, 'organization')}>{vol.organization || vol.name}</Editable>
                    <Editable className="font-bold text-[0.85em]" value={vol.duration || ''} onSave={save('volunteer', i, 'duration')}>{vol.duration}</Editable>
                  </div>
                  <div className="latex-subheading-row">
                    <Editable className="italic text-[0.85em]" value={vol.role || vol.title || ''} onSave={save('volunteer', i, 'role')}>{vol.role || vol.title}</Editable>
                    <Editable className="italic text-[0.85em]" value={vol.location || ''} onSave={save('volunteer', i, 'location')}>{vol.location}</Editable>
                  </div>
                  {vol.bullets?.length > 0 && (
                    <ul className="latex-bullets">
                      {vol.bullets.map((b, j) => (
                        <li key={j} className="bullet-wrapper">
                          <Editable tag="span" value={b} onSave={save('volunteer', i, 'bullets', j)}>{hl(b)}</Editable>
                          <DeleteItemBtn onClick={() => onDeleteItem(null, j, ['volunteer', i, 'bullets'])} title="Delete bullet" />
                        </li>
                      ))}
                    </ul>
                  )}
                </>
              )}
            </div>
          ))}
        </>
      )}

      {/* ── EXTRA SECTIONS (catch-all for anything not in known keys) ─── */}
      {extraSections.map((key) => {
        const value = data[key];
        const title = key
          .replace(/([A-Z])/g, ' $1')
          .replace(/^./, (s) => s.toUpperCase())
          .replace(/_/g, ' ');

        return (
          <div key={key} className="entry-avoid-break">
            <SectionHeader title={title} onDelete={() => onDeleteSection(key)} />
            {renderExtraValue(value, hl, key, onUpdate, onDeleteItem)}
          </div>
        );
      })}
    </div>
  );
}

// ─── Format an object item into readable text ─────────────────────────────────
function formatObjectItem(obj) {
  if (!obj || typeof obj !== 'object') return String(obj);
  // Try common field patterns to produce natural text
  const vals = Object.values(obj).filter((v) => v && typeof v === 'string');
  if (vals.length === 0) return '';
  // If there are exactly 2 values, join with " — " (e.g. "LeetCode — Solved 350+")
  if (vals.length === 2) return vals.join(' — ');
  // Otherwise join all values with ", "
  return vals.join(', ');
}

// ─── Render catch-all extra values (editable) ─────────────────────────────────
function renderExtraValue(value, hl, sectionKey, onUpdate, onDeleteItem) {
  if (typeof value === 'string') {
    return (
      <Editable tag="p" className="text-[0.92em] leading-relaxed" value={value} onSave={(v) => onUpdate([sectionKey], v)}>
        {hl ? hl(value) : value}
      </Editable>
    );
  }
  if (Array.isArray(value)) {
    return (
      <ul className="latex-bullets">
        {value.map((item, i) => {
          let text;
          if (typeof item === 'string') {
            text = item;
          } else if (typeof item === 'object' && item !== null) {
            text = formatObjectItem(item);
          } else {
            text = String(item);
          }
          return (
            <li key={i} className="bullet-wrapper">
              <Editable tag="span" value={text} onSave={(v) => onUpdate([sectionKey, i], v)}>
                {hl ? hl(text) : text}
              </Editable>
              <DeleteItemBtn onClick={() => onDeleteItem(sectionKey, i)} title="Delete item" />
            </li>
          );
        })}
      </ul>
    );
  }
  if (typeof value === 'object' && value !== null) {
    return (
      <ul className="latex-bullets">
        {Object.entries(value).map(([k, v]) => {
          const display = typeof v === 'string' ? v
            : typeof v === 'object' ? formatObjectItem(v)
            : String(v);
          return (
            <li key={k} className="bullet-wrapper">
              <span className="font-bold">{k}</span>:{' '}
              <Editable tag="span" value={display} onSave={(newVal) => onUpdate([sectionKey, k], newVal)}>
                {hl ? hl(display) : display}
              </Editable>
            </li>
          );
        })}
      </ul>
    );
  }
  return (
    <Editable tag="p" className="text-[0.92em]" value={String(value)} onSave={(v) => onUpdate([sectionKey], v)}>
      {String(value)}
    </Editable>
  );
}

// ─── Section Title ─────────────────────────────────────────────────────────────
function LatexSectionTitle({ children }) {
  return <h3 className="latex-section-title">{children}</h3>;
}

// ─── Contact Icons ─────────────────────────────────────────────────────────────
function PhoneIcon() {
  return <svg className="w-3 h-3" fill="currentColor" viewBox="0 0 512 512"><path d="M164.9 24.6c-7.7-18.6-28-28.5-47.4-23.2l-88 24C12.1 30.2 0 46 0 64C0 311.4 200.6 512 448 512c18 0 33.8-12.1 38.6-29.5l24-88c5.3-19.4-4.6-39.7-23.2-47.4l-96-40c-16.3-6.8-35.2-2.1-46.3 11.6L304.7 368C234.3 334.7 177.3 277.7 144 207.3L193.3 167c13.7-11.2 18.4-30 11.6-46.3l-40-96z" /></svg>;
}
function EnvelopeIcon() {
  return <svg className="w-3.5 h-3.5" fill="currentColor" viewBox="0 0 512 512"><path d="M48 64C21.5 64 0 85.5 0 112c0 15.1 7.1 29.3 19.2 38.4L236.8 313.6c11.4 8.5 27 8.5 38.4 0L492.8 150.4c12.1-9.1 19.2-23.3 19.2-38.4c0-26.5-21.5-48-48-48H48zM0 176V384c0 35.3 28.7 64 64 64H448c35.3 0 64-28.7 64-64V176L294.4 339.2c-22.8 17.1-54 17.1-76.8 0L0 176z" /></svg>;
}
function LinkedInIcon() {
  return <svg className="w-3 h-3" fill="currentColor" viewBox="0 0 448 512"><path d="M416 32H31.9C14.3 32 0 46.5 0 64.3v383.4C0 465.5 14.3 480 31.9 480H416c17.6 0 32-14.5 32-32.3V64.3c0-17.8-14.4-32.3-32-32.3zM135.4 416H69V202.2h66.5V416zm-33.2-243c-21.3 0-38.5-17.3-38.5-38.5S80.9 96 102.2 96c21.2 0 38.5 17.3 38.5 38.5 0 21.3-17.2 38.5-38.5 38.5zM384 416h-66.4V312c0-24.8-.5-56.7-34.5-56.7-34.6 0-39.9 27-39.9 54.9V416h-66.4V202.2h63.7v29.2h.9c8.9-16.8 30.6-34.5 62.9-34.5 67.2 0 79.7 44.3 79.7 101.9V416z" /></svg>;
}
function GitHubIcon() {
  return <svg className="w-3.5 h-3.5" fill="currentColor" viewBox="0 0 496 512"><path d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8z" /></svg>;
}
function GlobeIcon() {
  return <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M12 21a9.004 9.004 0 008.716-6.747M12 21a9.004 9.004 0 01-8.716-6.747M12 21c2.485 0 4.5-4.03 4.5-9S14.485 3 12 3m0 18c-2.485 0-4.5-4.03-4.5-9S9.515 3 12 3m0 0a8.997 8.997 0 017.843 4.582M12 3a8.997 8.997 0 00-7.843 4.582m15.686 0A11.953 11.953 0 0112 10.5c-2.998 0-5.74-1.1-7.843-2.918m15.686 0A8.959 8.959 0 0121 12c0 .78-.099 1.533-.284 2.253m0 0A17.919 17.919 0 0112 16.5c-3.162 0-6.133-.815-8.716-2.247m0 0A9.015 9.015 0 003 12c0-1.605.42-3.113 1.157-4.418" /></svg>;
}

export default App;
