import { escapeLatex, texBoldKeywords } from './textUtils';

// ─── Generate downloadable .tex source from resume JSON ────────────────────────
export function generateLatexSource(data) {
  const e = escapeLatex;
  const kw = data.jd_keywords || [];
  const bk = (text) => texBoldKeywords(text, kw);

  let tex = `%-------------------------
% Resume generated by ResumeBuilder AI
% Based on Jake Gutierrez's LaTeX template
%-------------------------

\\\\documentclass[letterpaper,11pt]{article}

\\\\usepackage{latexsym}
\\\\usepackage[empty]{fullpage}
\\\\usepackage{titlesec}
\\\\usepackage{marvosym}
\\\\usepackage[usenames,dvipsnames]{color}
\\\\usepackage{verbatim}
\\\\usepackage{enumitem}
\\\\usepackage[hidelinks]{hyperref}
\\\\usepackage{fancyhdr}
\\\\usepackage[english]{babel}
\\\\usepackage{tabularx}
\\\\usepackage{fontawesome5}
\\\\usepackage{multicol}
\\\\setlength{\\\\multicolsep}{-3.0pt}
\\\\setlength{\\\\columnsep}{-1pt}
\\\\input{glyphtounicode}

\\\\pagestyle{fancy}
\\\\fancyhf{}
\\\\fancyfoot{}
\\\\renewcommand{\\\\headrulewidth}{0pt}
\\\\renewcommand{\\\\footrulewidth}{0pt}

\\\\addtolength{\\\\oddsidemargin}{-0.6in}
\\\\addtolength{\\\\evensidemargin}{-0.5in}
\\\\addtolength{\\\\textwidth}{1.19in}
\\\\addtolength{\\\\topmargin}{-.7in}
\\\\addtolength{\\\\textheight}{1.4in}

\\\\urlstyle{same}
\\\\raggedbottom
\\\\raggedright
\\\\setlength{\\\\tabcolsep}{0in}

\\\\titleformat{\\\\section}{
  \\\\vspace{-4pt}\\\\scshape\\\\raggedright\\\\large\\\\bfseries
}{}{0em}{}[\\\\color{black}\\\\titlerule \\\\vspace{-5pt}]

\\\\pdfgentounicode=1

\\\\newcommand{\\\\resumeItem}[1]{\\\\item\\\\small{{#1 \\\\vspace{-2pt}}}}
\\\\newcommand{\\\\resumeSubheading}[4]{
  \\\\vspace{-2pt}\\\\item
    \\\\begin{tabular*}{1.0\\\\textwidth}[t]{l@{\\\\extracolsep{\\\\fill}}r}
      \\\\textbf{#1} & \\\\textbf{\\\\small #2} \\\\\\\\
      \\\\textit{\\\\small#3} & \\\\textit{\\\\small #4} \\\\\\\\
    \\\\end{tabular*}\\\\vspace{-7pt}
}
\\\\newcommand{\\\\resumeProjectHeading}[2]{
    \\\\item
    \\\\begin{tabular*}{1.001\\\\textwidth}{l@{\\\\extracolsep{\\\\fill}}r}
      \\\\small#1 & \\\\textbf{\\\\small #2}\\\\\\\\
    \\\\end{tabular*}\\\\vspace{-7pt}
}
\\\\newcommand{\\\\resumeSubItem}[1]{\\\\resumeItem{#1}\\\\vspace{-4pt}}
\\\\renewcommand\\\\labelitemi{$\\\\vcenter{\\\\hbox{\\\\tiny$\\\\bullet$}}$}
\\\\renewcommand\\\\labelitemii{$\\\\vcenter{\\\\hbox{\\\\tiny$\\\\bullet$}}$}
\\\\newcommand{\\\\resumeSubHeadingListStart}{\\\\begin{itemize}[leftmargin=0.0in, label={}]}
\\\\newcommand{\\\\resumeSubHeadingListEnd}{\\\\end{itemize}}
\\\\newcommand{\\\\resumeItemListStart}{\\\\begin{itemize}}
\\\\newcommand{\\\\resumeItemListEnd}{\\\\end{itemize}\\\\vspace{-5pt}}

\\\\begin{document}

`;

  // ── Heading ──
  const strip = (url) => (url || '').replace(/^https?:\/\//, '');
  tex += `\\\\begin{center}\\n    {\\\\Huge \\\\scshape ${e(data.name || '')}} \\\\\\\\ \\\\vspace{1pt}\\n`;
  if (data.location) tex += `    ${e(data.location)} \\\\\\\\ \\\\vspace{1pt}\\n`;
  tex += `    \\\\small`;
  if (data.phone) tex += ` \\\\raisebox{-0.1\\\\height}\\\\faPhone\\\\ ${e(data.phone)}`;
  if (data.email) tex += ` ~ \\\\href{mailto:${data.email}}{\\\\raisebox{-0.2\\\\height}\\\\faEnvelope\\\\  \\\\underline{${e(data.email)}}}`;
  if (data.linkedin) tex += ` ~ \\\\href{https://${strip(data.linkedin)}}{\\\\raisebox{-0.2\\\\height}\\\\faLinkedin\\\\ \\\\underline{${e(data.linkedin)}}}`;
  if (data.github) tex += ` ~ \\\\href{https://${strip(data.github)}}{\\\\raisebox{-0.2\\\\height}\\\\faGithub\\\\ \\\\underline{${e(data.github)}}}`;
  if (data.portfolio) tex += ` ~ \\\\href{https://${strip(data.portfolio)}}{\\\\raisebox{-0.2\\\\height}\\\\faGlobe\\\\ \\\\underline{${e(data.portfolio)}}}`;
  tex += `\\n    \\\\vspace{-8pt}\\n\\\\end{center}\\n\\n`;

  // ── Summary ──
  if (data.summary) {
    tex += `\\\\section{Summary}\\n\\\\small{${bk(data.summary)}}\\n\\\\vspace{-5pt}\\n\\n`;
  }

  // ── Education ──
  if (data.education?.length) {
    tex += `\\\\section{Education}\\n  \\\\resumeSubHeadingListStart\\n`;
    for (const edu of data.education) {
      tex += `    \\\\resumeSubheading\\n      {${e(edu.school || edu.institution || '')}}{${e(edu.year || '')}}\\n      {${e(edu.degree || '')}}{${e(edu.location || '')}${edu.gpa ? ' -- GPA: ' + e(edu.gpa) : ''}}\\n`;
    }
    tex += `  \\\\resumeSubHeadingListEnd\\n\\n`;
    const cw = data.education[0]?.coursework;
    if (cw?.length) {
      tex += `\\\\section{Relevant Coursework}\\n    \\\\begin{multicols}{4}\\n        \\\\begin{itemize}[itemsep=-5pt, parsep=3pt]\\n`;
      for (const c of cw) tex += `            \\\\item\\\\small ${e(c)}\\n`;
      tex += `        \\\\end{itemize}\\n    \\\\end{multicols}\\n    \\\\vspace*{2.0\\\\multicolsep}\\n\\n`;
    }
  }

  // ── Experience ──
  if (data.experience?.length) {
    tex += `\\\\section{Experience}\\n  \\\\resumeSubHeadingListStart\\n\\n`;
    for (const exp of data.experience) {
      tex += `    \\\\resumeSubheading\\n      {${e(exp.company || '')}}{${e(exp.duration || '')}}\\n      {${e(exp.title || exp.role || '')}}{${e(exp.location || '')}}\\n`;
      if (exp.bullets?.length) {
        tex += `      \\\\resumeItemListStart\\n`;
        for (const b of exp.bullets) tex += `        \\\\resumeItem{${bk(b)}}\\n`;
        tex += `      \\\\resumeItemListEnd\\n\\n`;
      }
    }
    tex += `  \\\\resumeSubHeadingListEnd\\n\\\\vspace{-16pt}\\n\\n`;
  }

  // ── Projects ──
  if (data.projects?.length) {
    tex += `\\\\section{Projects}\\n    \\\\vspace{-5pt}\\n    \\\\resumeSubHeadingListStart\\n`;
    for (const proj of data.projects) {
      const tech = Array.isArray(proj.techStack) ? proj.techStack.join(', ') : proj.tech || '';
      tex += `      \\\\resumeProjectHeading\\n          {\\\\textbf{${e(proj.name)}} $|$ \\\\emph{${e(tech)}}}{${e(proj.date || '')}}\\n`;
      tex += `          \\\\resumeItemListStart\\n`;
      const bullets = proj.bullets?.length ? proj.bullets : proj.description ? [proj.description] : [];
      for (const b of bullets) tex += `            \\\\resumeItem{${bk(b)}}\\n`;
      tex += `          \\\\resumeItemListEnd\\n          \\\\vspace{-13pt}\\n`;
    }
    tex += `    \\\\resumeSubHeadingListEnd\\n\\\\vspace{-15pt}\\n\\n`;
  }

  // ── Technical Skills (categorized) ──
  if (data.skill_categories && Object.keys(data.skill_categories).length) {
    tex += `\\\\section{Technical Skills}\\n \\\\begin{itemize}[leftmargin=0.15in, label={}]\\n    \\\\small{\\\\item{\\n`;
    for (const [cat, arr] of Object.entries(data.skill_categories)) {
      if (arr?.length) tex += `     \\\\textbf{${e(cat)}}{: ${arr.map(e).join(', ')}} \\\\\\\\\\n`;
    }
    tex += `    }}\\n \\\\end{itemize}\\n \\\\vspace{-16pt}\\n\\n`;
  } else if (data.skills?.length) {
    tex += `\\\\section{Technical Skills}\\n \\\\begin{itemize}[leftmargin=0.15in, label={}]\\n    \\\\small{\\\\item{\\n     \\\\textbf{Skills}{: ${data.skills.map(e).join(', ')}} \\\\\\\\\\n    }}\\n \\\\end{itemize}\\n \\\\vspace{-16pt}\\n\\n`;
  }

  // ── Certifications ──
  if (data.certifications?.length) {
    tex += `\\\\section{Certifications}\\n  \\\\resumeSubHeadingListStart\\n`;
    for (const cert of data.certifications) {
      if (typeof cert === 'string') tex += `    \\\\resumeSubItem{${e(cert)}}\\n`;
      else tex += `    \\\\resumeSubheading{${e(cert.name || '')}}{${e(cert.year || '')}}{${e(cert.issuer || '')}}{}\\n`;
    }
    tex += `  \\\\resumeSubHeadingListEnd\\n\\n`;
  }

  // ── Languages ──
  if (data.languages?.length) {
    tex += `\\\\section{Languages}\\n \\\\begin{itemize}[leftmargin=0.15in, label={}]\\n    \\\\small{\\\\item{${data.languages.map(e).join(', ')}}}\\n \\\\end{itemize}\\n\\\\vspace{-16pt}\\n\\n`;
  }

  // ── Awards ──
  if (data.awards?.length) {
    tex += `\\\\section{Awards}\\n  \\\\resumeItemListStart\\n`;
    for (const a of data.awards) tex += `    \\\\resumeItem{${e(typeof a === 'string' ? a : a.name || JSON.stringify(a))}}\\n`;
    tex += `  \\\\resumeItemListEnd\\n\\n`;
  }

  // ── Volunteer / Leadership ──
  if (data.volunteer?.length) {
    tex += `\\\\section{Leadership / Extracurricular}\\n  \\\\resumeSubHeadingListStart\\n`;
    for (const vol of data.volunteer) {
      if (typeof vol === 'string') tex += `    \\\\resumeSubItem{${e(vol)}}\\n`;
      else {
        tex += `    \\\\resumeSubheading{${e(vol.organization || vol.name || '')}}{${e(vol.duration || '')}}{${e(vol.role || vol.title || '')}}{${e(vol.location || '')}}\\n`;
        if (vol.bullets?.length) {
          tex += `      \\\\resumeItemListStart\\n`;
          for (const b of vol.bullets) tex += `        \\\\resumeItem{${e(b)}}\\n`;
          tex += `      \\\\resumeItemListEnd\\n`;
        }
      }
    }
    tex += `  \\\\resumeSubHeadingListEnd\\n\\n`;
  }

  tex += `\\\\end{document}\\n`;
  return tex;
}
